name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: angular-app
        run: npm ci

      - name: Lint
        working-directory: angular-app
        run: npm run lint

      - name: Run unit tests
        working-directory: angular-app
        run: npm run test:ci

      - name: Build production bundle
        working-directory: angular-app
        run: npm run build:prod
